// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"
)

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, created_at FROM accounts WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (email) VALUES ($1)
ON CONFLICT (email) DO NOTHING
`

// Lazily creates an account only once a magic-link token for the address has
// actually been consumed (RESEARCH.md Pattern 1) — never at "request link"
// time. ON CONFLICT DO NOTHING means a returning-visitor's second
// InsertAccount call is a no-op rather than an error; the row is then read
// back by GetAccountByEmail, since RETURNING would come back empty on the
// conflict path that matters most.
func (q *Queries) InsertAccount(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, insertAccount, email)
	return err
}
