// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_cooldowns.sql

package sqlcgen

import (
	"context"
	"time"
)

const claimEmailCooldown = `-- name: ClaimEmailCooldown :one
INSERT INTO email_cooldowns (email, last_requested_at)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE
SET last_requested_at = EXCLUDED.last_requested_at
WHERE email_cooldowns.last_requested_at <= $3
RETURNING last_requested_at
`

type ClaimEmailCooldownParams struct {
	Email          string
	RequestedAt    time.Time
	CooldownCutoff time.Time
}

// The per-address resend cooldown (IDENT-04, D-03/D-04). A single atomic
// claim, never a check followed by a separate insert — the second shape
// lets concurrent requests for one address all pass the check before any of
// them writes (T-01-93). The guard lives on the DO UPDATE, not the INSERT:
// when it is false, Postgres updates nothing and returns nothing, so a
// refused claim performs no write at all and cannot extend the window that
// refused it (DEC-J, DEC-X). sqlc's :one surfaces that as pgx.ErrNoRows —
// the same "no rows means refused" contract ConsumeToken already
// established in this codebase.
func (q *Queries) ClaimEmailCooldown(ctx context.Context, arg ClaimEmailCooldownParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, claimEmailCooldown, arg.Email, arg.RequestedAt, arg.CooldownCutoff)
	var last_requested_at time.Time
	err := row.Scan(&last_requested_at)
	return last_requested_at, err
}
