// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: magic_link_tokens.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertMagicLinkToken = `-- name: InsertMagicLinkToken :one
INSERT INTO magic_link_tokens (
    token_hash, email, expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, created_at, expires_at
`

type InsertMagicLinkTokenParams struct {
	TokenHash string
	Email     string
	ExpiresAt time.Time
}

type InsertMagicLinkTokenRow struct {
	ID        int64
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertMagicLinkToken(ctx context.Context, arg InsertMagicLinkTokenParams) (InsertMagicLinkTokenRow, error) {
	row := q.db.QueryRow(ctx, insertMagicLinkToken, arg.TokenHash, arg.Email, arg.ExpiresAt)
	var i InsertMagicLinkTokenRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}
