// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Email     string
	CreatedAt time.Time
}

type MagicLinkToken struct {
	ID        int64
	TokenHash string
	Email     string
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
}

type Report struct {
	ID                    int64
	SessionID             string
	Category              string
	Severity              string
	Description           string
	Latitude              float64
	Longitude             float64
	Geohash               string
	ShelterCapacityStatus *string
	ShelterHeadcount      *int32
	CreatedAt             time.Time
	ExpiresAt             time.Time
}

type Session struct {
	SessionID string
	CreatedAt time.Time
	AccountID *int64
}
