// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (
    session_id, category, severity, description, latitude, longitude, geohash,
    shelter_capacity_status, shelter_headcount, created_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
)
RETURNING id, category, severity, description, latitude, longitude, geohash,
          shelter_capacity_status, shelter_headcount, created_at, expires_at
`

type InsertReportParams struct {
	SessionID             string
	Category              string
	Severity              string
	Description           string
	Latitude              float64
	Longitude             float64
	Geohash               string
	ShelterCapacityStatus *string
	ShelterHeadcount      *int32
	CreatedAt             time.Time
	ExpiresAt             time.Time
}

type InsertReportRow struct {
	ID                    int64
	Category              string
	Severity              string
	Description           string
	Latitude              float64
	Longitude             float64
	Geohash               string
	ShelterCapacityStatus *string
	ShelterHeadcount      *int32
	CreatedAt             time.Time
	ExpiresAt             time.Time
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (InsertReportRow, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.SessionID,
		arg.Category,
		arg.Severity,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
		arg.Geohash,
		arg.ShelterCapacityStatus,
		arg.ShelterHeadcount,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i InsertReportRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Severity,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.Geohash,
		&i.ShelterCapacityStatus,
		&i.ShelterHeadcount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const nearbyReports = `-- name: NearbyReports :many
SELECT id, category, severity, description, latitude, longitude, geohash,
       shelter_capacity_status, shelter_headcount, created_at, expires_at, distance_km
FROM (
    SELECT id, category, severity, description, latitude, longitude, geohash,
           shelter_capacity_status, shelter_headcount, created_at, expires_at,
           ( 6371 * acos(
               least(1.0,
                 cos(radians($1::float8)) * cos(radians(latitude))
                 * cos(radians(longitude) - radians($2::float8))
                 + sin(radians($1::float8)) * sin(radians(latitude))
               )
             )
           )::float8 AS distance_km
    FROM reports
    WHERE expires_at > now()
      AND latitude  BETWEEN $3::float8 AND $4::float8
      AND longitude BETWEEN $5::float8 AND $6::float8
) AS candidates
WHERE distance_km <= $7::float8
ORDER BY distance_km ASC
`

type NearbyReportsParams struct {
	Lat      float64
	Lon      float64
	LatMin   float64
	LatMax   float64
	LonMin   float64
	LonMax   float64
	RadiusKm float64
}

type NearbyReportsRow struct {
	ID                    int64
	Category              string
	Severity              string
	Description           string
	Latitude              float64
	Longitude             float64
	Geohash               string
	ShelterCapacityStatus *string
	ShelterHeadcount      *int32
	CreatedAt             time.Time
	ExpiresAt             time.Time
	DistanceKm            float64
}

func (q *Queries) NearbyReports(ctx context.Context, arg NearbyReportsParams) ([]NearbyReportsRow, error) {
	rows, err := q.db.Query(ctx, nearbyReports,
		arg.Lat,
		arg.Lon,
		arg.LatMin,
		arg.LatMax,
		arg.LonMin,
		arg.LonMax,
		arg.RadiusKm,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NearbyReportsRow
	for rows.Next() {
		var i NearbyReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Severity,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Geohash,
			&i.ShelterCapacityStatus,
			&i.ShelterHeadcount,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.DistanceKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reporterAccountsForReports = `-- name: ReporterAccountsForReports :many
SELECT r.id AS report_id, s.account_id AS reporter_account_id
FROM reports r
LEFT JOIN sessions s ON r.session_id = s.session_id
WHERE r.id = ANY($1::bigint[])
`

type ReporterAccountsForReportsRow struct {
	ReportID          int64
	ReporterAccountID *int64
}

// Batched sibling of ReportVoteContext's reporter half (internal/store/
// queries/votes.sql), reused for a whole feed page instead of one report.
//
// (a) Why it exists at all. service.BuildVoteTally(rows, reportID,
// reporterAccountID) needs each report's reporter account to route the
// reporter's own resolution vote into ReporterResolved and to exclude the
// reporter's rows from the independent counts. Passing nil here on the read
// path would mean ReporterResolved never fires on a read, and a report whose
// reporter marked it resolved would keep appearing in the live feed — a
// direct D-12/D-13 failure. The same value also decides the response's
// is_own_report flag (D-03).
//
// (b) Why it is batched rather than per report. The feed returns a whole
// page. One call with the page's ids costs one round trip; a per-report
// lookup would be an N+1 — the exact shape CurrentVotesForReports was
// designed as a batch to avoid.
//
// (c) Why it is a separate query instead of a join added to NearbyReports.
// NearbyReports is pinned byte-for-byte by a drift const and its plan is
// asserted by an EXPLAIN-based index test. Leaving it untouched keeps
// FOUND-03's proven bounding-box/Haversine query exactly as Phase 1 shipped
// it, and — the load-bearing part — makes it self-evident that the feed
// query gained no visibility or vote predicate of its own
// (.planning/research/ARCHITECTURE.md Anti-Pattern 1, threat T-02-04).
// Filtering by visibility happens in Go, over Resolve's output, never in
// SQL.
//
// (d) Why LEFT JOIN and not INNER JOIN. reports.session_id carries no
// foreign key and sessions.account_id is nullable — both deliberate, both
// documented in migration 00002. A report submitted before Phase 1.1 made
// login mandatory, and any report seeded by internal/testutil/seed.go
// (which inserts a literal session_id with no matching sessions row),
// therefore has no account-bound session. An INNER JOIN would drop those
// reports from this result entirely, and the caller could not distinguish
// "no reporter account" from "report not in the batch." With the LEFT JOIN
// every requested-and-existing report comes back, carrying a NULL
// reporter_account_id: nobody matches it, is_own_report is false for every
// viewer, and the report stays in the feed exactly as it does today. Note
// also that sessions.session_id is the table's PRIMARY KEY, so the join
// matches at most one row and can never duplicate a report.
//
// (e) Why the join stops at sessions. sessions.account_id IS accounts.id by
// foreign key, so a third join through accounts could only re-confirm a row
// the constraint already guarantees. Omitted on purpose, matching
// ReportVoteContext's own reasoning.
func (q *Queries) ReporterAccountsForReports(ctx context.Context, reportIds []int64) ([]ReporterAccountsForReportsRow, error) {
	rows, err := q.db.Query(ctx, reporterAccountsForReports, reportIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReporterAccountsForReportsRow
	for rows.Next() {
		var i ReporterAccountsForReportsRow
		if err := rows.Scan(&i.ReportID, &i.ReporterAccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportsByAccount = `-- name: ReportsByAccount :many
SELECT r.id, r.category, r.severity, r.description, r.latitude, r.longitude, r.geohash,
       r.shelter_capacity_status, r.shelter_headcount, r.created_at, r.expires_at
FROM reports r
JOIN sessions s ON r.session_id = s.session_id
WHERE s.account_id = $1
ORDER BY r.created_at DESC
`

type ReportsByAccountRow struct {
	ID                    int64
	Category              string
	Severity              string
	Description           string
	Latitude              float64
	Longitude             float64
	Geohash               string
	ShelterCapacityStatus *string
	ShelterHeadcount      *int32
	CreatedAt             time.Time
	ExpiresAt             time.Time
}

// Joins through the session's bound account rather than filtering on
// r.session_id directly (01.1-07-PLAN.md's whole point): one account can
// hold multiple verified sessions (multi-device, D-10), and this is the
// query that must surface all of them together. A plain INNER JOIN is
// equivalent here to a defensive LEFT JOIN — an orphaned report has no
// session row and therefore no bound account, so the WHERE clause below
// filters it out either way (DEC-M). No expiry predicate: a person's own
// history does not vanish from their own profile when a report ages out of
// the public feed. No session_id in the selected columns, continuing
// T-01-02's control (TestNearbyReportsExcludesSessionID) — Phase 2/3's
// independence predicate must count distinct account, with the session
// identifier retained only as the write-path column (IDENT-05).
func (q *Queries) ReportsByAccount(ctx context.Context, accountID *int64) ([]ReportsByAccountRow, error) {
	rows, err := q.db.Query(ctx, reportsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportsByAccountRow
	for rows.Next() {
		var i ReportsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Severity,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Geohash,
			&i.ShelterCapacityStatus,
			&i.ShelterHeadcount,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
