// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (
    session_id, category, severity, description, latitude, longitude, geohash,
    shelter_capacity_status, shelter_headcount, created_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
)
RETURNING id, category, severity, description, latitude, longitude, geohash,
          shelter_capacity_status, shelter_headcount, created_at, expires_at
`

type InsertReportParams struct {
	SessionID             string
	Category              string
	Severity              string
	Description           string
	Latitude              float64
	Longitude             float64
	Geohash               string
	ShelterCapacityStatus *string
	ShelterHeadcount      *int32
	CreatedAt             time.Time
	ExpiresAt             time.Time
}

type InsertReportRow struct {
	ID                    int64
	Category              string
	Severity              string
	Description           string
	Latitude              float64
	Longitude             float64
	Geohash               string
	ShelterCapacityStatus *string
	ShelterHeadcount      *int32
	CreatedAt             time.Time
	ExpiresAt             time.Time
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (InsertReportRow, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.SessionID,
		arg.Category,
		arg.Severity,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
		arg.Geohash,
		arg.ShelterCapacityStatus,
		arg.ShelterHeadcount,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i InsertReportRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Severity,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.Geohash,
		&i.ShelterCapacityStatus,
		&i.ShelterHeadcount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
