// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
)

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (session_id)
VALUES ($1)
ON CONFLICT (session_id) DO NOTHING
`

func (q *Queries) UpsertSession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, upsertSession, sessionID)
	return err
}
