// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package sqlcgen

import (
	"context"
	"time"
)

const currentVotesForReports = `-- name: CurrentVotesForReports :many
SELECT DISTINCT ON (report_id, account_id, kind)
    report_id, account_id, kind, value, geohash_cell, created_at
FROM votes
WHERE report_id = ANY($1::bigint[])
ORDER BY report_id, account_id, kind, created_at DESC, id DESC
`

type CurrentVotesForReportsRow struct {
	ReportID    int64
	AccountID   int64
	Kind        string
	Value       string
	GeohashCell string
	CreatedAt   time.Time
}

// DISTINCT ON (report_id, account_id, kind) latest-row-wins read over a
// batch of report ids. This single batched read is what makes the
// distinct-account half of TRUST-03's independence predicate automatic —
// the result already holds at most one row per (report, account, kind), so
// 02-03's independence counting only has to count distinct geohash_cell
// values over it. It takes an array of report ids so the feed path in
// 02-04 can load votes for a whole page of reports in one query rather
// than N+1.
func (q *Queries) CurrentVotesForReports(ctx context.Context, reportIds []int64) ([]CurrentVotesForReportsRow, error) {
	rows, err := q.db.Query(ctx, currentVotesForReports, reportIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentVotesForReportsRow
	for rows.Next() {
		var i CurrentVotesForReportsRow
		if err := rows.Scan(
			&i.ReportID,
			&i.AccountID,
			&i.Kind,
			&i.Value,
			&i.GeohashCell,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVote = `-- name: InsertVote :exec
INSERT INTO votes (report_id, account_id, kind, value, geohash_cell)
VALUES ($1, $2, $3, $4, $5)
`

type InsertVoteParams struct {
	ReportID    int64
	AccountID   int64
	Kind        string
	Value       string
	GeohashCell string
}

// A bare append with no conflict resolution and no row lock. created_at is
// deliberately omitted so the column default supplies it. Concurrency
// safety for TRUST-09 comes from Postgres handling concurrent plain inserts
// into an unconstrained table natively — nothing here needs serialising.
func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) error {
	_, err := q.db.Exec(ctx, insertVote,
		arg.ReportID,
		arg.AccountID,
		arg.Kind,
		arg.Value,
		arg.GeohashCell,
	)
	return err
}
