// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package sqlcgen

import (
	"context"
	"time"
)

const currentVotesForReports = `-- name: CurrentVotesForReports :many
SELECT DISTINCT ON (report_id, account_id, kind)
    report_id, account_id, kind, value, geohash_cell, created_at
FROM votes
WHERE report_id = ANY($1::bigint[])
ORDER BY report_id, account_id, kind, created_at DESC, id DESC
`

type CurrentVotesForReportsRow struct {
	ReportID    int64
	AccountID   int64
	Kind        string
	Value       string
	GeohashCell string
	CreatedAt   time.Time
}

// DISTINCT ON (report_id, account_id, kind) latest-row-wins read over a
// batch of report ids. This single batched read is what makes the
// distinct-account half of TRUST-03's independence predicate automatic —
// the result already holds at most one row per (report, account, kind), so
// 02-03's independence counting only has to count distinct geohash_cell
// values over it. It takes an array of report ids so the feed path in
// 02-04 can load votes for a whole page of reports in one query rather
// than N+1.
func (q *Queries) CurrentVotesForReports(ctx context.Context, reportIds []int64) ([]CurrentVotesForReportsRow, error) {
	rows, err := q.db.Query(ctx, currentVotesForReports, reportIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentVotesForReportsRow
	for rows.Next() {
		var i CurrentVotesForReportsRow
		if err := rows.Scan(
			&i.ReportID,
			&i.AccountID,
			&i.Kind,
			&i.Value,
			&i.GeohashCell,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVote = `-- name: InsertVote :exec
INSERT INTO votes (report_id, account_id, kind, value, geohash_cell)
VALUES ($1, $2, $3, $4, $5)
`

type InsertVoteParams struct {
	ReportID    int64
	AccountID   int64
	Kind        string
	Value       string
	GeohashCell string
}

// A bare append with no conflict resolution and no row lock. created_at is
// deliberately omitted so the column default supplies it. Concurrency
// safety for TRUST-09 comes from Postgres handling concurrent plain inserts
// into an unconstrained table natively — nothing here needs serialising.
func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) error {
	_, err := q.db.Exec(ctx, insertVote,
		arg.ReportID,
		arg.AccountID,
		arg.Kind,
		arg.Value,
		arg.GeohashCell,
	)
	return err
}

const reportVoteContext = `-- name: ReportVoteContext :one
SELECT r.severity, r.category, r.expires_at, s.account_id AS reporter_account_id
FROM reports r
LEFT JOIN sessions s ON r.session_id = s.session_id
WHERE r.id = $1
`

type ReportVoteContextRow struct {
	Severity          string
	Category          string
	ExpiresAt         time.Time
	ReporterAccountID *int64
}

// The single read VotingService.CastVote makes before deciding anything
// (02-03a). Four points a later reader would otherwise "correct":
//
// (a) Why one query instead of two. CastVote needs the reporter identity,
// the severity/category pair Resolve needs as ReportMeta, and expires_at on
// every single call. Reading all four in one statement removes a window in
// which a report could expire or be deleted between a separate reporter
// lookup and a separate meta read. This query supersedes the narrower
// ReporterAccountID query 02-02/02-PATTERNS.md/02-RESEARCH.md anticipated;
// that query is deliberately never created.
//
// (b) Why the join stops at sessions. sessions.account_id IS accounts.id —
// a foreign key onto that column. A third join through accounts could only
// re-confirm what the foreign key already guarantees, at the cost of an
// extra join, so it is omitted on purpose.
//
// (c) Why LEFT JOIN and not INNER JOIN. reports.session_id carries no
// foreign key, and sessions.account_id is nullable — both deliberate, both
// documented in migration 00002. A report submitted before Phase 1.1 made
// login mandatory therefore has no account-bound session. An INNER JOIN
// would return zero rows for such a report, indistinguishable from "no
// such report," and the report would become unvotable. The LEFT JOIN
// returns a NULL reporter_account_id instead: nobody matches it, the D-03
// self-vote block correctly does not fire, and the report stays votable.
// Zero rows then means exactly one thing — the report id does not exist.
//
// (d) What this query is for. The reporter identity for D-03's self-vote
// block, the severity/category pair for ReportMeta, and expires_at for the
// expired-report rejection.
func (q *Queries) ReportVoteContext(ctx context.Context, reportID int64) (ReportVoteContextRow, error) {
	row := q.db.QueryRow(ctx, reportVoteContext, reportID)
	var i ReportVoteContextRow
	err := row.Scan(
		&i.Severity,
		&i.Category,
		&i.ExpiresAt,
		&i.ReporterAccountID,
	)
	return i, err
}
